name: job_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  get_it: ^7.6.6
  injectable: ^2.3.2
  intl: ^0.19.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFProMedium
      fonts:
        - asset: fonts/SF-Pro-Display-Medium.otf
    - family: SFProRegular
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
    - family: SFProSemibold
      fonts:
        - asset: fonts/SF-Pro-Display-Semibold.otf
